### ISSUE TITLE
Python error - The error was: KeyError: 'body'

### ISSUE THREAD

**Issue by enrik90h** [ReconInfoSec/ansible-graylog-modules#11]
Hi,

I have this error:

```
root@DESKTOP-O90K5P8:~/ansible-graylog-lib# ansible-playbook -i /root/playbooks/inventory list_input.yml


PLAY [localhost] ****************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Display all inputs] *******************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'body'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1646224677.9164226-42195067791243/AnsiballZ_graylog_input.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1646224677.9164226-42195067791243/AnsiballZ_graylog_input.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1646224677.9164226-42195067791243/AnsiballZ_graylog_input.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.graylog_input', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_graylog_input_payload_qewhkv0l/ansible_graylog_input_payload.zip/ansible/modules/graylog_input.py\", line 199, in <module>\n  File \"/tmp/ansible_graylog_input_payload_qewhkv0l/ansible_graylog_input_payload.zip/ansible/modules/graylog_input.py\", line 173, in main\n  File \"/tmp/ansible_graylog_input_payload_qewhkv0l/ansible_graylog_input_payload.zip/ansible/modules/graylog_input.py\", line 132, in get_token\nKeyError: 'body'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```

With this playbook test:
```
root@DESKTOP-O90K5P8:~/ansible-graylog-lib# cat list_input.yml
---
- hosts: localhost
  connection: local
  vars:
    - endpoint: "http://localhost:9000/api"
    - graylog_user: admin
    - graylog_password: admin
  tasks:
    - name: Display all inputs
      graylog_input:
        endpoint: "{{ endpoint }}"
        graylog_user: "{{ graylog_user }}"
        graylog_password: "{{ graylog_password }}"
        allow_http: "true"
        validate_certs: "false"
        action: "list"
```
