### ISSUE TITLE
Bug in Graylog_streams.py for Graylog 3.x

### ISSUE THREAD

**Issue by ion-storm** [ReconInfoSec/ansible-graylog-modules#2]
Example Task to reproduce:
```
    - name: Create stream
      graylog_streams:
        action: create
        endpoint: "{{ endpoint }}"
        graylog_user: "{{ graylog_user }}"
        graylog_password: "{{ graylog_password }}"
        title: "{{ stream_name }}"
        description: "{{ stream_desc }}"
        matching_type: "AND"
        remove_matches_from_default_stream: True
        rules:
          - {"field":"message","type":1,"value":"test_stream rule","inverted": false,"description":"test_stream rule"}
```

The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1558120641.39-158998988338179/AnsiballZ_graylog_streams.py", line 113, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1558120641.39-158998988338179/AnsiballZ_graylog_streams.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1558120641.39-158998988338179/AnsiballZ_graylog_streams.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_graylog_streams_payload_N_qF4Q/__main__.py", line 739, in <module>
  File "/tmp/ansible_graylog_streams_payload_N_qF4Q/__main__.py", line 700, in main
  File "/tmp/ansible_graylog_streams_payload_N_qF4Q/__main__.py", line 605, in default_index_set
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1558120641.39-158998988338179/AnsiballZ_graylog_streams.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1558120641.39-158998988338179/AnsiballZ_graylog_streams.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1558120641.39-158998988338179/AnsiballZ_graylog_streams.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_graylog_streams_payload_N_qF4Q/__main__.py\", line 739, in <module>\n  File \"/tmp/ansible_graylog_streams_payload_N_qF4Q/__main__.py\", line 700, in main\n  File \"/tmp/ansible_graylog_streams_payload_N_qF4Q/__main__.py\", line 605, in default_index_set\n  File \"/usr/lib/python2.7/json/__init__.py\", line 339, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/lib/python2.7/json/decoder.py\", line 364, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/lib/python2.7/json/decoder.py\", line 382, in raw_decode\n    raise ValueError(\"No JSON object could be decoded\")\nValueError: No JSON object could be decoded\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```
